### ISSUE TITLE
Zugang via Plugin Website und nicht /admin/....

### ISSUE THREAD

**Issue by Woersty** [svethi/Loxberry-Plugin-Fritz.Lox#1]
Ich habe heute meinen Fritz!DECT 210 erfolgreich in Betrieb genommen. Funktioniert tadellos.
Allerdings würde ich mir wünschen, einen extra Benutzer verwenden zu können und das Plugin über seine Plugin URL und nicht über die Admin Seite (/admin/) anzusprechen.

**Comment by svethi** [comment]
Du kannst doch in der Fritzbox den gewünschten User anlegen und dann auch verwenden.
Der Zugang über die gesicherte Seite ist gewollt so, da man sonst auch ohne LB Interface die Fritzbox ohne Passwort steuern könnte.
